import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import ApolloProviderLayout from "./providers/apollo-provider";
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import queryClient from "./providers/tanStack-provider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryClientProvider client={queryClient}>
        <ApolloProviderLayout>
          <Toaster />
          {children}
        </ApolloProviderLayout>
        </QueryClientProvider>
      </body>
    </html>
  );
}
